### ISSUE TITLE
camera_info_manager_py

### ISSUE THREAD

**Issue by vwueest** [fabianschilling/openmv_cam#4]
Thanks for the wrapper, works great for me!
On melodic, Ubuntu 18.04, I had to install camera_info_manager_py. If others run into the issue of catkin build requesting it to be installed, I would suggest you add something along the lines of,
`roscd`
`cd ../src`
`git clone https://github.com/ros-perception/camera_info_manager_py.git`
to the README.

**Comment by fabianschilling** [comment]
Fixed by #5
